### ISSUE TITLE
Can't parse var blocks

### ISSUE THREAD

**Issue by Kaiochao** [SpaceManiac/SpacemanDMM#77] opened 2019-05-07 11:03 UTC
For var "blocks" of the form:
```js
var
  a
  b
  c
```
The `var` keyword doesn't get highlighted.

Inside procs (for local vars), you get an error:
`got '{', expected one of: '/', identifier`

**Comment by SpaceManiac** [comment] 2019-05-07 21:03
Duplicate of #45

**Closed by SpaceManiac** 2019-05-07 21:03 UTC
